services:
  # Medusa Server
  # This service runs the Medusa backend application
  # and the admin dashboard.
  medusa:
    image: ghcr.io/tosinshada/test-shop:latest
    container_name: medusa_backend
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://root:Wpg22nLnTY7NhFQM6H4KscmA8NsT2Arsf4@db:5432/medusa-test-shop
      - STORE_CORS=http://localhost:8000,https://docs.medusajs.com
      - ADMIN_CORS=http://localhost:5173,http://localhost:9000,https://docs.medusajs.com,https://test-shop.thezentra.com
      - AUTH_CORS=http://localhost:5173,http://localhost:9000,http://localhost:8000,https://docs.medusajs.com,https://test-shop.thezentra.com
      - MEDUSA_BACKEND_URL=http://localhost:9000
    env_file:
      - .env
    networks:
      - medusa_network

networks:
  medusa_network:
    driver: bridge