services:
  # Medusa Server
  # This service runs the Medusa backend application
  # and the admin dashboard.
  medusa:
    build: .
    container_name: medusa_backend
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - STORE_CORS=http://localhost:8000,https://docs.medusajs.com
      - ADMIN_CORS=http://localhost:5173,http://localhost:9000,https://docs.medusajs.com
      - AUTH_CORS=http://localhost:5173,http://localhost:9000,http://localhost:8000,https://docs.medusajs.com
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - medusa_network

networks:
  medusa_network:
    driver: bridge